blog/urls.py
from django.conf.urls import url
from .views import PostListView, PostDetailView, contact


app_name = 'blog'

urlpatterns = [
    url(r'^$', PostListView.as_view(), name='post_list'),
    url(r'^contact/$',contact , name='contact'),
    url(r'^(?P<slug>[\w-]+)/$', PostDetailView.as_view(), name='post_detail'),
]

mysite/urls.py
from django.conf.urls import include, url
from django.contrib import admin

urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'^', include('blog.urls')),
]

blog/models.py
from django.db import models
from django.db.models.signals import pre_save
from .utils import unique_slug_generator


class Post(models.Model):
    title = models.CharField(max_length=150)
    body = models.TextField()
    date = models.DateTimeField(auto_now_add=True)
    updated = models.DateTimeField(auto_now=True)
    slug = models.SlugField(null=True, blank=True)

    def __str__(self):
        return self.title


def post_pre_save_receiver(sender, instance, *args, **kwargs):
    if not instance.slug:
        instance.slug = unique_slug_generator(instance)

pre_save.connect(post_pre_save_receiver, sender=Post)

blog/views.py
from django.shortcuts import render
from django.views.generic import ListView, DetailView
from .models import Post


class PostListView(ListView):
    queryset = Post.objects.all().order_by('-date')
    template_name = 'blog.html'
    paginate_by = 3


class PostDetailView(DetailView):
    template_name = 'post.html'
    queryset = Post.objects.all()


def contact(request):
    return render(request, 'contact.html')

blog/templates/blog.html
{% extends "header.html" %}

{% block content %}
    {% for post in object_list %}
    	 <div class="post_content"> 
	        <h2><a href="{% url 'blog:post_detail' post.slug %}"> {{ post.title }}</a></h2>
	        <small>Published: {{ post.date }}</small>
	        <p>{{ post.body|truncatewords:30 }}</p>
	        <a href="{{ post.slug }}" class="btn btn-info">Read More</a>
        </div>
    {% endfor %}
    <div class="paginate text-center">
    	{% if is_paginated %}
		  <ul class="pagination">
		    {% if page_obj.has_previous %}
		      <li><a href="?page={{ page_obj.previous_page_number }}">&laquo;</a></li>
		    {% else %}
		      <li class="disabled"><span>&laquo;</span></li>
		    {% endif %}
		    {% for i in paginator.page_range %}
		      {% if page_obj.number == i %}
		        <li class="active"><span>{{ i }} <span class="sr-only">(current)</span></span></li>
		      {% else %}
		        <li><a href="?page={{ i }}">{{ i }}</a></li>
		      {% endif %}
		    {% endfor %}
		    {% if page_obj.has_next %}
		      <li><a href="?page={{ page_obj.next_page_number }}">&raquo;</a></li>
		    {% else %}
		      <li class="disabled"><span>&raquo;</span></li>
		    {% endif %}
	  	</ul>
	{% endif %}
    </div>
    
{% endblock %}

blog/templates/contact.html
{% extends "header.html" %}

{% block content %}
    <p>Saifur</p>
{% endblock %}

blog/templates/header.html
<!DOCTYPE html>
<html lang="en">
   <head>
            <title>Saifur</title>
            <meta charset="utf-8"/>
            {% load staticfiles %}
            <link rel="stylesheet" href="{% static 'css/bootstrap.min.css' %}" type="text/css"/>
            <link rel="stylesheet" href="{% static 'css/style.css' %}" type="text/css"/>
            <link href="https://fonts.googleapis.com/css?family=Roboto+Slab" rel="stylesheet">

    </head>

    <body>
        <header>
            <div class="container">
                <div class="col-md-6 col-md-offset-3">
                     <div class="heading text-center">
                        <h1>Saifur's Blog</h1>
                        <h3>Python lover from Bangladesh</h3>
                     </div>

                    <nav class="navbar navbar-default">
                  
                        <!-- Brand and toggle get grouped for better mobile display -->
                        <div class="navbar-header">
                          <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1" aria-expanded="false">
                            <span class="sr-only">Toggle navigation</span>
                            <span class="icon-bar"></span>
                            <span class="icon-bar"></span>
                            <span class="icon-bar"></span>
                          </button>
                          <a class="navbar-brand" href="#"></a>
                        </div>

                        <!-- Collect the nav links, forms, and other content for toggling -->
                        <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
                          <ul class="nav navbar-nav">

                            <li><a href="{% url 'blog:post_list' %}">Home</a></li>
                            <li><a href="https://www.facebook.com/shimu.reehman">About</a></li>
                            <li><a href="https://www.linkedin.com/in/saifur-rahman-798b37136/">LinkedIn</a></li>
                            <li><a href="https://github.com/Saifur43">Github</a></li>
                            <li><a href="https://www.facebook.com/shimu.reehman">Facebook</a></li>
                            
                          </ul>
                        </div><!-- /.navbar-collapse -->
                    </nav>


                </div>
           
            </div><!-- /.container-fluid -->
            

        </header>

        <hr class="header_hr">

        <section id="blog"> 
               <div class='container'>
                    <div class="row">
                        <div class="col-md-6 col-md-offset-3">
                           
                                {% block content %}

                                {% endblock %}
                            </div>
                            
                        </div>       
                    </div>
                    
                </div>
        </section> 
          

    </body>

</html>

blog/templates/post.html
{% extends "header.html" %}
{% block content %}
  
    	
    		


    	<div class="post_content">
    		<h3><a href="{% url 'blog:post_detail' post.slug %}"> {{ post.title }}</a></h3>
	        <small>Published: {{ post.date }}</small>
	        <p>{{ post.body|safe|linebreaks }}</p>
	        

	        <div id="disqus_thread"></div>
				<script>

				/**
				*  RECOMMENDED CONFIGURATION VARIABLES: EDIT AND UNCOMMENT THE SECTION BELOW TO INSERT DYNAMIC VALUES FROM YOUR PLATFORM OR CMS.
				*  LEARN WHY DEFINING THESE VARIABLES IS IMPORTANT: https://disqus.com/admin/universalcode/#configuration-variables*/
				/*
				var disqus_config = function () {
				this.page.url = PAGE_URL;  // Replace PAGE_URL with your page's canonical URL variable
				this.page.identifier = PAGE_IDENTIFIER; // Replace PAGE_IDENTIFIER with your page's unique identifier variable
				};
				*/
				(function() { // DON'T EDIT BELOW THIS LINE
				var d = document, s = d.createElement('script');
				s.src = 'https://djangoblog-2.disqus.com/embed.js';
				s.setAttribute('data-timestamp', +new Date());
				(d.head || d.body).appendChild(s);
				})();
				</script>
				<noscript>Please enable JavaScript to view the <a href="https://disqus.com/?ref_noscript">comments powered by Disqus.</a></noscript>
		</div>

        
    <br><br>
{% endblock %}